import { Card, Group, SegmentedControl, SimpleGrid, Stack, Text, Title } from '@mantine/core'
import { useState } from 'react'
import { useOverview, useProtocols } from '../api'
import { AlertList } from '../components/AlertList'
import { ProtocolChart } from '../components/ProtocolChart'
